version: '3'
services:
   redis-server:
     image: "redis"
   node-app: 
      build:

        container_name: spring
        dockerfile: Dockerfile
        context: ./
    
      ports: 
         - "80:3000"
